
export interface Race {
  id: string;
  name: string;
  circuit: string;
  img: string;
  badge: string;
  blurb: string;
  date: string;
  region: string;
  raced?: boolean;
}

export const F1_CALENDAR_2026: Race[] = [
  {
    id: "bahrain",
    name: "Bahrain GP",
    circuit: "Bahrain International Circuit",
    img: "/races/bahrain.jpg",
    badge: "01 MAR",
    blurb: "El inicio de temporada bajo las luces del desierto.",
    date: "2026-03-01T15:00:00",
    region: "Medio Oriente",
    raced: true,
  },
  {
    id: "saudi-arabian",
    name: "Saudi Arabian GP",
    circuit: "Jeddah Corniche Circuit",
    img: "/races/jedah.png",
    badge: "15 MAR",
    blurb: "El circuito urbano más rápido del mundo, rozando los muros.",
    date: "2026-03-15T17:00:00",
    region: "Medio Oriente",
    raced: true,
  },
  {
    id: "australian",
    name: "Australian GP",
    circuit: "Albert Park Circuit",
    img: "/races/albert-park.jpg",
    badge: "29 MAR",
    blurb: "Clásico parque urbano en Melbourne con zonas de alta velocidad.",
    date: "2026-03-29T04:00:00",
    region: "Oceanía",
    raced: true,
  },
  {
    id: "japanese",
    name: "Japanese GP",
    circuit: "Suzuka International Racing Course",
    img: "/races/Japan.jpg",
    badge: "12 ABR",
    blurb: "El icónico trazado en forma de 8, favorito de los pilotos.",
    date: "2026-04-12T05:00:00",
    region: "Asia",
    raced: true,
  },
  {
    id: "chinese",
    name: "Chinese GP",
    circuit: "Shanghai International Circuit",
    img: "/races/china.png",
    badge: "26 ABR",
    blurb: "Largas rectas y la infame y técnica primera curva del caracol.",
    date: "2026-04-26T07:00:00",
    region: "Asia",
    raced: true,
  },
  {
    id: "miami",
    name: "Miami GP",
    circuit: "Miami International Autodrome",
    img: "/races/miami.png",
    badge: "10 MAY",
    blurb: "Glamour, yates falsos y pura acción alrededor del estadio.",
    date: "2026-05-10T19:30:00",
    region: "Norteamérica",
    raced: true,
  },
  {
    id: "emilia-romagna",
    name: "Emilia Romagna GP",
    circuit: "Autodromo Enzo e Dino Ferrari",
    img: "/races/imola.jpg",
    badge: "24 MAY",
    blurb: "Historia pura y un trazado de la vieja escuela sin margen de error.",
    date: "2026-05-24T13:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "monaco",
    name: "Monaco GP",
    circuit: "Circuit de Monaco",
    img: "/races/monaco.jpg",
    badge: "31 MAY",
    blurb: "La joya de la corona. Clasificar acá lo es todo.",
    date: "2026-05-31T13:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "canadian",
    name: "Canadian GP",
    circuit: "Circuit Gilles-Villeneuve",
    img: "/races/canada.png",
    badge: "14 JUN",
    blurb: "Curvas rápidas, chicanas y el famoso Muro de los Campeones.",
    date: "2026-06-14T18:00:00",
    region: "Norteamérica",
    raced: true,
  },
  {
    id: "spanish",
    name: "Spanish GP",
    circuit: "Circuito de Madrid IFEMA",
    img: "/races/madrid.png",
    badge: "28 JUN",
    blurb: "¡Nueva pista urbana e híbrida por las calles de la capital española!",
    date: "2026-06-28T13:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "austrian",
    name: "Austrian GP",
    circuit: "Red Bull Ring",
    img: "/races/austria.png",
    badge: "05 JUL",
    blurb: "Pista corta en las montañas con tres zonas de DRS consecutivas.",
    date: "2026-07-05T13:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "british",
    name: "British GP",
    circuit: "Silverstone Circuit",
    img: "/races/silverstone.jpg",
    badge: "12 JUL",
    blurb: "La cuna de la F1. Maggots y Becketts ponen a prueba la aerodinámica.",
    date: "2026-07-12T14:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "belgian",
    name: "Belgian GP",
    circuit: "Circuit de Spa-Francorchamps",
    img: "/races/spa.png",
    badge: "26 JUL",
    blurb: "La pista más larga del año y el espectacular paso por Eau Rouge.",
    date: "2026-07-26T13:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "hungarian",
    name: "Hungarian GP",
    circuit: "Hungaroring",
    img: "/races/hungary.png",
    badge: "02 AGO",
    blurb: "Apodado 'Mónaco sin muros', requiere máxima carga aerodinámica.",
    date: "2026-08-02T13:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "dutch",
    name: "Dutch GP",
    circuit: "Circuit Zandvoort",
    img: "/races/dutch.png",
    badge: "30 AGO",
    blurb: "Curvas peraltadas y un mar naranja en las dunas holandesas.",
    date: "2026-08-30T13:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "italian",
    name: "Italian GP",
    circuit: "Autodromo Nazionale Monza",
    img: "/races/monza.png",
    badge: "06 SEP",
    blurb: "El Templo de la Velocidad. Acelerador a fondo frente a los Tifosi.",
    date: "2026-09-06T13:00:00",
    region: "Europa",
    raced: true,
  },
  {
    id: "azerbaijan",
    name: "Azerbaijan GP",
    circuit: "Baku City Circuit",
    img: "/races/baku.jpg",
    badge: "20 SEP",
    blurb: "Largas rectas y la estrechísima sección del castillo.",
    date: "2026-09-20T11:00:00",
    region: "Asia",
    raced: false,
  },
  {
    id: "singapore",
    name: "Singapore GP",
    circuit: "Marina Bay Street Circuit",
    img: "/races/signapur.jpg",
    badge: "04 OCT",
    blurb: "Calor extremo y máxima exigencia física bajo las luces nocturnas.",
    date: "2026-10-04T12:00:00",
    region: "Asia",
    raced: false,
  },
  {
    id: "united-states",
    name: "United States GP",
    circuit: "Circuit of The Americas",
    img: "/races/austin.jpg",
    badge: "18 OCT",
    blurb: "Elevación extrema en la curva 1 y mucho espectáculo en Texas.",
    date: "2026-10-18T19:00:00",
    region: "Norteamérica",
    raced: false,
  },
  {
    id: "mexico-city",
    name: "Mexico City GP",
    circuit: "Autódromo Hermanos Rodríguez",
    img: "/races/mejico.jpg",
    badge: "25 OCT",
    blurb: "Alta altitud que exige a los motores y el increíble paso por el Foro Sol.",
    date: "2026-10-25T20:00:00",
    region: "Norteamérica",
    raced: false,
  },
  {
    id: "s-o-paulo",
    name: "São Paulo GP",
    circuit: "Autódromo José Carlos Pace",
    img: "/races/interlagos.jpg",
    badge: "08 NOV",
    blurb: "Carreras impredecibles, clima cambiante y la 'S' de Senna.",
    date: "2026-11-08T17:00:00",
    region: "Sudamérica",
    raced: false,
  },
  {
    id: "las-vegas",
    name: "Las Vegas GP",
    circuit: "Las Vegas Strip Circuit",
    img: "/races/las_vegas.jpg",
    badge: "21 NOV",
    blurb: "Velocidad extrema directo por el Strip en la noche del sábado.",
    date: "2026-11-21T06:00:00",
    region: "Norteamérica",
    raced: false,
  },
  {
    id: "qatar",
    name: "Qatar GP",
    circuit: "Lusail International Circuit",
    img: "/races/qtar.jpg",
    badge: "29 NOV",
    blurb: "Un trazado rápido y fluido en medio del desierto nocturno.",
    date: "2026-11-29T16:00:00",
    region: "Medio Oriente",
    raced: false,
  },
  {
    id: "abu-dhabi",
    name: "Abu Dhabi GP",
    circuit: "Yas Marina Circuit",
    img: "/races/yas_marina.jpg",
    badge: "06 DIC",
    blurb: "El gran cierre de temporada, empezando de día y terminando de noche.",
    date: "2026-12-06T13:00:00",
    region: "Medio Oriente",
    raced: false,
  }
];