export const CALENDAR_TICKER = [
  { name: "GP de Australia — Albert Park", raced: true },
  { name: "GP de China — Shanghái", raced: true },
  { name: "GP de Japón — Suzuka", raced: true },
  { name: "GP de Miami — Miami International Autodrome", raced: true },
  { name: "GP de Canadá — Gilles Villeneuve", raced: true },
  { name: "GP de Mónaco — Monte Carlo", raced: true },
  { name: "GP de España — Barcelona-Catalunya", raced: true },
  { name: "GP de Austria — Red Bull Ring", raced: true },
  { name: "GP de Gran Bretaña — Silverstone", raced: true },
  { name: "GP de Bélgica — Spa-Francorchamps", raced: true },
  { name: "GP de Hungría — Hungaroring", raced: true },
  { name: "GP de Países Bajos — Zandvoort", raced: true },
  { name: "GP de Italia — Monza", raced: false },
  { name: "GP de Madrid — Madring Circuit", raced: false },
  { name: "GP de Azerbaiyán — Bakú", raced: false },
  { name: "GP de Singapur — Marina Bay", raced: false },
  { name: "GP de Estados Unidos — Austin", raced: false },
  { name: "GP de México — Hermanos Rodríguez", raced: false },
  { name: "GP de San Pablo — Interlagos", raced: false },
  { name: "GP de Las Vegas — Las Vegas Strip", raced: false },
  { name: "GP de Qatar — Lusail", raced: false },
  { name: "GP de Abu Dabi — Yas Marina", raced: false }
];